apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  selector:
    matchLabels:
      app: crawler
  replicas: 1
  template:
    metadata:
      labels: 
        app: crawler
    spec:
      containers:
      - name: crawler-container
        image: >-
          registry.aggregatoricapaci.com/car-doctor/dev/dantri-crawler:latest
        ports:
        - name: "crawler-port"
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: acregistry
      dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
      app: crawler
  ports:
  - port: 8080
    targetPort: 8080
