apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd # The volume plugin to use for provisioning the PV
patameters:                       # The params passed to the provisioner
  type: pd-ssd
  zone: europe-west1-b
