apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: kubia
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Pod
metadata:
  name: kubia-test
spec:
  containers:
  - image: luksa/kubia
    name: kubia-test
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
---
apiVersion: v1
kind: Pod
metadata:
  name: kubia-test-2
spec:
  containers:
  - image: luksa/kubia
    name: kubia-test
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
