# vindocker/k8s-probe-demo uses nginx
# nginx will start after 10s
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: probe-demo
    image: vinsdocker/k8s-probe-demo
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /live.html
        port: 80
      periodSeconds: 1
      failureThreshold: 3
