version: '3'

services:
  redis-server:
    image: redis:latest
    container_name: my-redis
    expose: ['6379']
    ports: 
      - "6379:6379"
    networks:
      - mysql_default
    volumes:
      - redis-volume:/data

networks:
  mysql_default:
    driver: bridge

volumes:
  redis-volume:
    driver: local
