apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v1"
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template:
    metadata:
      labels: 
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: vinsdocker/k8s-app:v1
        ports:
        - name: "app-port"
          containerPort: 80
