apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
<<<<<<< HEAD:Dev-Ops/k8s/k8s-in-action/6.Volumes/6.5-Decoupling-pods-from-the-underlying-storage-tech/mongodb-pv-nfs.yaml
    server: 172.17.0.1
    path: /var/nfs
=======
    path: "/nfs/data"
    server: 127.0.0.1
>>>>>>> origin/feature/home/develop:Dev-Ops/k8s/k8s-in-action/6.Volumes/6.5-Decoupling-pods-from-the-underlying-storage-tech/6.5.2-Creating-PersistentVolume/mongodb-pv-nfs.yaml
