apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  #type: NodePort
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: http
      #nodePort: 30123
  - name: https
    port: 443
    targetPort: https
      #nodePort: 30124
      #sessionAffinity: ClientIP
  selector:
    app: kubia
