apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never # Always, Never, OnFailure
  containers:
  - name: entrypoint
    image: vinsdocker/k8s-entrypoint
    command:
      - "date"
