apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
data:
  MONGO_INITDB_ROOR_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOR_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4=
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ=
