apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-a
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.18.0.1
    path: /var/nfs/k8s-practive/staeful-set/pv-a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-b
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.18.0.1
    path: /var/nfs/k8s-practive/staeful-set/pv-b
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-c
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.18.0.1
    path: /var/nfs/k8s-practive/staeful-set/pv-c
