apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never # Always, Never, OnFailure
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "request.timeout"
      value: "10ms"
    - name: "spring.profile.active"
      value: "dev"
    args:
      - "env"
