apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi  # Requesting 1 GiB of storage
  accessModes:
  - ReadWriteOnce   # Storage support a single client (performing both reads and writes)_
  storageClassName: ""
