apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  app.key: |
    YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnTWFwCm1ldGFkYXRhOgogIG5hbWU6IGFwcC1wcm9w
    ZXJ0aWVzCmRhdGE6CiAgYXBwVXJsOiAiaHR0cDovL215LWFwcC1zZXJ2aWNlIgogIHRpbWVvdXQ6
    ICIzMCIKLS0tCmFwaVZlcnNpb246IHYxCmtpbmQ6IFBvZAptZXRhZGF0YToKICBuYW1lOiBteS1w
    b2QKc3BlYzoKICByZXN0YXJ0UG9saWN5OiBOZXZlcgogIGNvbnRhaW5lcnM6CiAgLSBuYW1lOiB1
    YnVudHUKICAgIGltYWdlOiB1YnVudHUKICAgIGVudjogIAogICAgLSBuYW1lOiAicmVxdWVzdC50
    aW1lb3V0IgogICAgICB2YWx1ZUZyb206CiAgICAgICAgY29uZmlnTWFwS2V5UmVmOgogICAgICAg
    ICAgbmFtZTogYXBwLXByb3BlcnRpZXMKICAgICAgICAgIGtleTogdGltZW91dAogICAgLSBuYW1l
    OiAiYXBwbGljYXRpb24udXJsIgogICAgICB2YWx1ZUZyb206CiAgICAgICAgY29uZmlnTWFwS2V5
    UmVmOgogICAgICAgICAgbmFtZTogYXBwLXByb3BlcnRpZXMKICAgICAgICAgIGtleTogYXBwVXJs
    CiAgICBhcmdzOgogICAgLSBlbnYK
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeridSeconds: 1
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: secret-volume
      mountPath: /usr/share/props
    args:
    - sleep
    - "3600"
  volumes:
  - name: secret-volume
    secret:
      name: app-secret
