apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
spec:
  nodeSelector: # nodeSelector tells K8s to deploy this pod to nodes containing the gpu=true label
    gpu: "true"
  containers:
  - image: luksa/kubia
    name: kubia
