
# a very minimal declarative config file
_format_version: "2.1"
_transform: true

database = postgres             # Determines the database (or no database) for                                 # this node
                                 # Accepted values are `postgres` and `off`.

pg_host = postgres             # Host of the Postgres server.
pg_port = 5432                  # Port of the Postgres server.
pg_timeout = 5000               # Defines the timeout (in ms), for connecting,
                                 # reading and writing.

pg_user = admin_konggateway                  # Postgres user.
pg_password = 1                  # Postgres user's password.
pg_database = kong_gateway              # The database name to connect to.

pg_schema = kong_gateway                     # The database schema to use. If unspecified,
                                 # Kong will respect the `search_path` value of
                                 # your PostgreSQL instance.
