version: "3"
services: 
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product-service
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    enviroment:
#      - PGADMIN_DEFAULT_EMAIL=admin
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    volumes:
#      - ./docker-volume/pgadmin:/var/lib/pgadmin
#    ports:
#      - 9000:80
